homepageTab = Startseite
homepageShowShopBuilderContentLabel = Shop Builder Startseite anzeigen
defaultHomepageLabel = Standardstartseite anzeigen
homepageSliderItemId1Label = ID der Artikelvariante, die auf der ersten Folie des Image Sliders angezeigt wird
homepageSliderImageUrl1Label = URL des Artikelbildes auf der ersten Folie
homepageSliderItemId2Label = ID der Artikelvariante, die auf der zweiten Folie des Image Sliders angezeigt wird
homepageSliderImageUrl2Label = URL des Artikelbildes auf der zweiten Folie
homepageSliderItemId3Label = ID der Artikelvariante, die auf der dritten Folie des Image Sliders angezeigt wird
homepageSliderImageUrl3Label = URL des Artikelbildes auf der dritten Folie
homepageHeroExtraItemId1Label = ID der Artikelvariante, die in der oberen Artikelvorschau angezeigt wird
homepageHeroExtraImageUrl1Label = URL des Artikelbildes in der oberen Artikelvorschau
homepageHeroExtraItemId2Label = ID der Artikelvariante, die in der unteren Artikelvorschau angezeigt wird
homepageHeroExtraImageUrl2Label = URL des Artikelbildes in der unteren Artikelvorschau
homepageHomepageCategory1Label = Artikelkategorie, die in der ersten Kategorievorschau angezeigt wird
homepageHomepageCategory2Label = Artikelkategorie, die in der zweiten Kategorievorschau angezeigt wird
homepageHomepageCategory3Label = Artikelkategorie für die erste Artikelliste
homepageHomepageCategory4Label = Artikelkategorie, die in der dritten Kategorievorschau angezeigt wird
homepageHomepageCategory5Label = Artikelkategorie, die in der vierten Kategorievorschau angezeigt wird
homepageHomepageCategory6Label = Artikelkategorie für die zweite Artikelliste
