homepageTab = Startseiten Slider Oben - Bilder Hochladen unter Webspace - /p2k19/img/home/
homepageShowShopBuilderContentLabel = Shop Builder Startseite anzeigen
defaultHomepageLabel = Standardstartseite anzeigen

homepageSliderItemId1Label = Erste Folie - Verlinkung
homepageSliderImageUrl1Label = Erste Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig1Label = Erste Folie Alt und Titel Text
homepageSliderItemDateFrom1Label = Erste Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil1Label = Erste Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId2Label = Zweite Folie - Verlinkung
homepageSliderImageUrl2Label = Zweite Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig2Label = Zweite Folie Alt und Titel Text
homepageSliderItemDateFrom2Label = Zweite Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil2Label = Zweite Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId3Label = Dritte Folie - Verlinkung
homepageSliderImageUrl3Label = Dritte Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig3Label = Dritte Folie Alt und Titel Text
homepageSliderItemDateFrom3Label = Dritte Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil3Label = Dritte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId4Label = Vierte Folie - Verlinkung
homepageSliderImageUrl4Label = Vierte Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig4Label = Vierte Folie Alt und Titel Text
homepageSliderItemDateFrom4Label = Vierte Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil4Label = Vierte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId5Label = Fünfte Folie - Verlinkung
homepageSliderImageUrl5Label = Fünfte Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig5Label = Fünfte Folie Alt und Titel Text
homepageSliderItemDateFrom5Label = Fünfte Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil5Label = Fünfte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId6Label = Fünfte Folie - Verlinkung
homepageSliderImageUrl6Label = Fünfte Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig6Label = Fünfte Folie Alt und Titel Text
homepageSliderItemDateFrom6Label = Fünfte Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil6Label = Fünfte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepageSliderItemId7Label = Fünfte Folie - Verlinkung
homepageSliderImageUrl7Label = Fünfte Folie - Bild URL (ohne _550.webp, _980.webp, _1920.jpg usw. wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepageSliderItemTextBig7Label = Fünfte Folie Alt und Titel Text
homepageSliderItemDateFrom7Label = Fünfte Folie Startdatum (YYYY-MM-DD)
homepageSliderItemDateUntil7Label = Fünfte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

highlighthomepageTab = Startseite Highlight Slider - Bilder Hochladen unter Webspace - /p2k19/img/home/ Größe _550 und _980
homepagehigSliderItemId1Label = Erste Folie - Verlinkung
homepagehigSliderImageUrl1Label = Erste Folie - Bild URL (ohne _550.webp, _980.webp wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepagehigSliderItemTextBig1Label = Erste Folie Alt und Titel Text
homepagehigSliderItemDateFrom1Label = Erste Folie Startdatum (YYYY-MM-DD)
homepagehigSliderItemDateUntil1Label = Erste Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepagehigSliderItemId2Label = Zweite Folie - Verlinkung
homepagehigSliderImageUrl2Label = Zweite Folie -  Bild URL (ohne _550.webp, _980.webp wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepagehigSliderItemTextBig2Label = Zweite Folie Alt und Titel Text
homepagehigSliderItemDateFrom2Label = Zweite Folie Startdatum (YYYY-MM-DD)
homepagehigSliderItemDateUntil2Label = Zweite Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepagehigSliderItemId3Label = Dritte Folie - Verlinkung
homepagehigSliderImageUrl3Label = Dritte Folie - Bild URL (ohne _550.webp, _980.webp wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepagehigSliderItemTextBig3Label = Dritte Folie Alt und Titel Text
homepagehigSliderItemDateFrom3Label = Dritte Folie Startdatum (YYYY-MM-DD)
homepagehigSliderItemDateUntil3Label = Dritte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepagehigSliderItemId4Label = Vierte Folie - Verlinkung
homepagehigSliderImageUrl4Label = Vierte Folie - Bild URL (ohne _550.webp, _980.webp wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepagehigSliderItemTextBig4Label = Vierte Folie Alt und Titel Text
homepagehigSliderItemDateFrom4Label = Vierte Folie Startdatum (YYYY-MM-DD)
homepagehigSliderItemDateUntil4Label = Vierte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)

homepagehigSliderItemId5Label = Fünfte Folie - Verlinkung
homepagehigSliderImageUrl5Label = Fünfte Folie - Bild URL (ohne _550.webp, _980.webp wird selbst zugewiesen), falls URL nicht vorhanden, wird dieser Slider ausgeblendet
homepagehigSliderItemTextBig5Label = Fünfte Folie Alt und Titel Text
homepagehigSliderItemDateFrom5Label = Fünfte Folie Startdatum (YYYY-MM-DD)
homepagehigSliderItemDateUntil5Label = Fünfte Folie Enddatum (YYYY-MM-DD) (an diesem Datum wird das Bild NICHT mehr angezeigt)
